package com.dawn.catlovers.core.database.mapper

import com.dawn.catlovers.core.database.CatBreedEntity
import com.dawn.catlovers.core.model.CatBreed

fun CatBreedEntity.asExternalModel(): CatBreed = CatBreed(
    id = id,
    name = name,
    origin = origin,
    countryCode = countryCode,
    description = description,
    temperament = temperament.split("|").filter { it.isNotBlank() },
    lifeSpan = lifeSpan,
    weightMetric = weightMetric,
    imageUrl = imageUrl,
    wikipediaUrl = wikipediaUrl,
    hypoallergenic = hypoallergenic,
    indoor = indoor,
    lap = lap,
    affectionLevel = affectionLevel,
    childFriendly = childFriendly,
    dogFriendly = dogFriendly,
    energyLevel = energyLevel,
    grooming = grooming,
    intelligence = intelligence,
    socialNeeds = socialNeeds,
    vocalisation = vocalisation,
    sheddingLevel = sheddingLevel,
    coatLength = coatLength,
    isFavorite = isFavorite,
)

fun CatBreed.asEntity(updatedAtMillis: Long): CatBreedEntity = CatBreedEntity(
    id = id,
    name = name,
    origin = origin,
    countryCode = countryCode,
    description = description,
    temperament = temperament.joinToString("|"),
    lifeSpan = lifeSpan,
    weightMetric = weightMetric,
    imageUrl = imageUrl,
    wikipediaUrl = wikipediaUrl,
    hypoallergenic = hypoallergenic,
    indoor = indoor,
    lap = lap,
    affectionLevel = affectionLevel,
    childFriendly = childFriendly,
    dogFriendly = dogFriendly,
    energyLevel = energyLevel,
    grooming = grooming,
    intelligence = intelligence,
    socialNeeds = socialNeeds,
    vocalisation = vocalisation,
    sheddingLevel = sheddingLevel,
    coatLength = coatLength,
    isFavorite = isFavorite,
    updatedAtMillis = updatedAtMillis,
)
